CREATE TABLE PATIENT (
PatientID INT PRIMARY KEY,
FullName VARCHAR(100),
DateOfBirth DATE,
Gender VARCHAR(10),
Phone VARCHAR(20),
Email VARCHAR(100)
);

CREATE TABLE DOCTOR (
DoctorID INT PRIMARY KEY,
FullName VARCHAR(100),
Specialty VARCHAR(100),
Phone VARCHAR(20),
HireDate DATE
);

CREATE TABLE APPOINTMENT (
AppointmentID INT PRIMARY KEY,
PatientID INT,
DoctorID INT,
Date DATE,
Time TIME,
Status VARCHAR(20),
FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID),
FOREIGN KEY (DoctorID) REFERENCES DOCTOR(DoctorID)
);

CREATE TABLE MEDICAL_RECORD (
RecordID INT PRIMARY KEY,
AppointmentID INT UNIQUE,
Diagnosis VARCHAR(200),
Notes VARCHAR(300),
CreatedDate DATE,
FOREIGN KEY (AppointmentID) REFERENCES APPOINTMENT(AppointmentID)
);

CREATE TABLE PRESCRIPTION (
PrescriptionID INT PRIMARY KEY,
RecordID INT,
Medication VARCHAR(100),
Dosage VARCHAR(50),
Duration VARCHAR(50),
FOREIGN KEY (RecordID) REFERENCES MEDICAL_RECORD(RecordID)
);

CREATE TABLE BILL (
BillID INT PRIMARY KEY,
AppointmentID INT UNIQUE,
ConsultationFee DECIMAL(10,2),
MedicationCost DECIMAL(10,2),
TotalAmount DECIMAL(10,2),
Status VARCHAR(20),
FOREIGN KEY (AppointmentID) REFERENCES APPOINTMENT(AppointmentID)
);
